cuda_version:
    # - cuda90
    # - cuda91
    # - cuda92
    # - cuda100
    # - cuda101
    - cuda102
    # - cuda110
cxx_compiler_version:
    # - 5
    # - 5
    # - 5
    # - 7
    # - 7
    - 7
    # - 8
numpy:
    - 1.14.1

zip_keys:
    - cuda_version
    - cxx_compiler_version
