# Copyright (c) 2021 Regents of the University of California
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

{% set number = GIT_DESCRIBE_NUMBER %}

package:
  name: "tsnecuda"
  version: "3.0.0"

source:
  git_url: ../../

build:
  number: {{ number }}

outputs:
  - name: tsnecuda
    build:
      string: "h{{ PKG_HASH }}_{{ number }}_cuda{{ cudatoolkit }}"
      script: "cd ../../build/build_{{ cudatoolkit }} && $PYTHON setup.py install --single-version-externally-managed --record=record.txt --prefix=$PREFIX"
    requirements:
      run:
        - openblas
        - faiss-gpu ==1.6.5
        - numpy >=1.14
        - python {{ python }}
        - cudatoolkit {{ cudatoolkit }}
    test:
      imports:
        - tsnecuda
        - tsnecuda.TSNE

about:
  home: https://github.com/CannyLab/tsne-cuda
  license: LICENSE.txt
  license_family: BSD
  license_file: "LICENSE.txt"
  summary: CUDA Implementation of T-SNE with Python bindings
  description:
    "===========\ntsnecuda\n===========\n\ntsnecuda provides an optimized CUDA implementation of the T-SNE algorithm by L Van der Maaten. tsnecuda is able to compute the T-SNE of large numbers\
    \ of points up to 1200 times faster than other leading libraries, and provides simple python bindings with a SKLearn style interface::\n\n    #!/usr/bin/env python\n\n    from tsnecuda import TSNE\n\
    \    embeddedX = TSNE(n_components=2).fit_transform(X)\n\nFor more information, check out the repository at https://github.com/rmrao/tsne-cuda. \n\n\n"
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - DavidMChan
