#ifndef __DEFS_H_
#define __DEFS_H_

#include <float.h>

#define PROXIMITY_THREADS 128


#define CUCKOO_TABLE_NUM 3
#define CUCKOO_BLOCK_SIZE 512
#define CUCKOO_MULTIHASH_PER_BLOCK_SIZE 576
#define CUCKOO_HASH_PER_BLOCK_SIZE (CUCKOO_MULTIHASH_PER_BLOCK_SIZE / CUCKOO_TABLE_NUM)
#define CUCKOO_MAX_ATTEMPT 25
#define CUCKOO_HASH_PARAMETER 409
#define CUCKOO_HASH_THREADS 128

#define LSH_M 32
#define LSH_nP 32
#define LSH_MAXSORT 800

#define MAX_BLOCKS_PER_DIMENSION 65535

#ifndef CUDART_NORM_HUGE_F
#define CUDART_NORM_HUGE_F FLT_MAX
#endif

#endif